version: '3.8'
services:
  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT #nombre de la imagen que hemos creado
    restart: always
    container_name: eureka-server
    ports:
      - '8761:8761'
    networks:
      - 'dockernetflix-network'
  zuul-service:
    image: zuul:0.0.1-SNAPSHOT #nombre de la imagen que hemos creado
    restart: always
    container_name: zuul
    ports:
      - '7000:7000'
    networks:
      - 'dockernetflix-network'
  greeting-microservice:
    image: greeting-microservice:0.0.1-SNAPSHOT #nombre de la imagen que hemos creado
    restart: always
    container_name: greeting-microservice
    networks:
      - 'dockernetflix-network'
  greetings-telegram:
    image: greetings-telegram:0.0.1-SNAPSHOT #nombre de la imagen que hemos creado
    restart: always
    container_name: greetings-telegram
    networks:
      - 'dockernetflix-network'
networks:
  dockernetflix-network: #necesitamos crear en una red para alojar los servicios en ella y que puedan comunicarse entre sí
 