spring:
  application:
    name: zuul-service
 
#Tomcat Embedded Server Configuration
server:
  port: 7000
 
#Zuul Configuration Properties
zuul:
  routes:
      serv-greet:
        path: /greeting-service/**
        serviceId: greeting-microservice
      serv-greet2:
        path: /greeting-service-telegram/**
        serviceId: greetings-telegram
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka