spring:
  application:
    name: greetings-telegram
    version: 0.0.1-SNAPSHOT 
 
#Tomcat Embedded Server Configuration
server: 
  port: 8002
 
#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka

#Telegram Configuration Properties
telegram:
  url: https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s
  apiToken: 1616522199:AAE3fFzgl3HSnRPo85kT9MPOwyRL7AwoxDU
  chatId: -1001386235816